[package]
name = "SwitchboardFeedParser"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/deps/move-stdlib", rev = "devnet" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }
switchboard = { git = "https://github.com/switchboard-xyz/sbv2-sui.git", subdir = "move/switchboard/", rev = "main"  }

[addresses]
switchboard_feed_parser = "0x0"
std = "0x1"
sui =  "0x2"
switchboard =  "0x8c8b750023fbd573955c431fb4395e7e396aaca3"
